<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
             xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy"
             xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://impl.ws.demo.zj.com/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/"
             targetNamespace="http://impl.ws.demo.zj.com/" name="PersonServiceImplService">
    <import namespace="http://ws.demo.zj.com/" location="http://localhost:8888/ws/person?wsdl=1"/>
    <binding xmlns:ns1="http://ws.demo.zj.com/" name="PersonServiceImplPortBinding" type="ns1:PersonService">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
        <operation name="addPerson">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal" namespace="http://ws.demo.zj.com/"/>
            </input>
            <output>
                <soap:body use="literal" namespace="http://ws.demo.zj.com/"/>
            </output>
        </operation>
        <operation name="getAllPersons">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal" namespace="http://ws.demo.zj.com/"/>
            </input>
            <output>
                <soap:body use="literal" namespace="http://ws.demo.zj.com/"/>
            </output>
        </operation>
        <operation name="getPerson">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal" namespace="http://ws.demo.zj.com/"/>
            </input>
            <output>
                <soap:body use="literal" namespace="http://ws.demo.zj.com/"/>
            </output>
        </operation>
        <operation name="deletePerson">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal" namespace="http://ws.demo.zj.com/"/>
            </input>
            <output>
                <soap:body use="literal" namespace="http://ws.demo.zj.com/"/>
            </output>
        </operation>
    </binding>
    <service name="PersonServiceImplService">
        <port name="PersonServiceImplPort" binding="tns:PersonServiceImplPortBinding">
            <soap:address location="http://localhost:8888/ws/person"/>
        </port>
    </service>
</definitions>